### ISSUE TITLE
Todo

### ISSUE THREAD

**Issue by Samuel-James2003** [Samuel-James2003/OngunFinalProj#4]
- [ ] Login client travailleur
- [ ] Base de donnée partie dashboard (client et travailleur)

**Comment by Samuel-James2003** [comment]
- [ ] Bug FillNavBar

**Comment by Samuel-James2003** [comment]
##Dashboard
- [ ] Add and edit page (they can be the same page)
	-  Use session to save the values of the or just redo the search with the Id
- [ ] Delete
	- Delete is a simple sql query

##General
- [ ] Add to NavbarFilling a second option that takes a person id and writes the name on the right side of the page and a link to clear the session variable and back to main screen page. 

##Contact and About Us
- [ ] Add fluff all these pages (probably using chatgpt)

**Comment by Samuel-James2003** [comment]
## Admin
- [ ] If user is admin you need to have an extra menu options
- [ ] Admin can see/edit/delete all tasks
- [ ] Admin can chose a worker to a worker or a client (How i understand this is the admin creates the link through the pivot tables from client to worker ) 

## User pages
- [ ] User page
	- [ ] Edit profile modify-add-delete
	- [ ] Edit status modify-add-delete

## Chat
- [ ] Link to the running instance of a chatroom (maybe trasfer data in the url id destination and id sender)

**Comment by SamuelHerreraHerrera** [comment]
Can you check the dashboard to see if i made a mistake with the delete button

**Comment by Samuel-James2003** [comment]
## Edit 

- [ ] 2 ifs 
	- [ ] admin has 3 boxed (bools) for complete
	- [ ] client and worker has one box for their responsiblitliy 
- [ ] sql to modify the 2 tables
